version: '{build}'
image: Visual Studio 2015

environment:
  matrix:
  #- PlatformToolset: v140_xp
  - PlatformToolset: v120_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    #- Debug

install:
    - git submodule -q update --init
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build_script:
- ps: |
    Write-Output "Configuration: $env:CONFIGURATION"
    Write-Output "Platform: $env:PLATFORM"
    $generator = switch ($env:PLATFORMTOOLSET)
    {
        "v140" {"Visual Studio 14 2015"}
        "v140_xp" {"Visual Studio 14 2015"}
        "v120" {"Visual Studio 12 2013"}
        "v120_xp" {"Visual Studio 12 2013"}
    }
    if ($env:PLATFORM -eq "x64")
    {
        $generator = "$generator Win64"
    }
    mkdir build
    cd build
    cmake -D ENABLE_TRACE=ON -D BUILD_CLAR=OFF -D MSVC_CRTDBG=ON .. -G"$generator"
    cmake --build . --config $env:CONFIGURATION

after_build:
    - cd c:\projects\libgit2\build
    - ps: >-
        $npplibgit2FileName = "git2.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "libgit2\build\x64\Release\git2.dll" -FileName "$npplibgit2FileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "libgit2\build\Release\git2.dll" -FileName "$npplibgit2FileName"
        }
